# By: Riasat Ullah

# access page names
error_404 = '404.html'
change_password = 'change_password.html'
login = 'login.html'
forgot_credentials = 'forgot_credentials.html'
history = 'history.html'
invalid_client_type = 'invalid_client_type.html'
open_invoices = 'open_invoices.html'
payments = 'payments.html'
reports = 'reports.html'
settings = 'settings.html'
upload_invoice = 'upload_invoice.html'

# admin page names
add_client = 'add_client.html'
add_relation = 'add_relation.html'
admin_clients = 'admin_clients.html'
admin_client_profile = 'admin_client_profile.html'
admin_history = 'admin_history.html'
admin_invalid_client_type = 'admin_invalid_client_type.html'
admin_login = 'admin_login.html'
admin_open_invoices = 'admin_open_invoices.html'
admin_payments = 'admin_payments.html'
client_edit_relations = 'client_edit_relations.html'
client_history = 'client_history.html'
client_limits = 'client_limits.html'
client_open_invoices = 'client_open_invoices.html'
client_relations = 'client_relations.html'
client_repayment = 'client_repayment.html'
client_users = 'client_users.html'
edit_client_limits = 'edit_client_limits.html'
edit_relation_limits = 'edit_relation_limits.html'

# page titles
title_clients = 'Clients'
title_forgot_credentials = 'Forgot Credentials'
title_history = 'History'
title_limits = 'Limits'
title_login = 'Login'
title_open_invoices = 'Open Invoices'
title_payments = 'Payments'
title_relations = 'Relations'
title_repayment = 'Repayment'
title_reports = 'Reports'
title_settings = 'Settings'
title_upload_invoice = 'Upload Invoice'
title_users = 'Users'
