# this file has all the variable names for
# parameters that are passed into html files

# common
active = 'active'
admin = 'admin'
address = 'address'
amount = 'amount'
city = 'city'
country = 'country'
currency = 'currency'
description = 'description'
edit = 'edit'
edit_relation = 'edit_relation'
end_date = 'end_date'
industry = 'industry'
invoice_id = 'invoice_id'
page_type = 'page_type'
phone = 'phone'
previous_page = 'previous_page'
registration = 'registration'
row_count = 'row_count'
row_multiplier = 'row_multiplier'
start_date = 'start_date'
tax_pin = 'tax_pin'
user_type = 'user_type'

# forgot credentials page
credential_type = 'credential_type'

# all
confirm_password = 'confirm_password'
data = 'data'
has_errors = 'has_errors'
login_error = 'login_error'
login_failed = 'login_failed'
messages = 'messages'
new_password = 'new_password'
notes = 'notes'
password = 'password'
request_submitted = 'request_submitted'
title = 'title'
updated_by = 'updated_by'
updated_timestamp = 'updated_timestamp'
username = 'username'

# users
answer_1 = 'answer_1'
answer_2 = 'answer_2'
birth_date = 'birth_date'
cell_phone = 'cell_phone'
email = 'email'
first_name = 'first_name'
hash_password = 'hash_password'
id = 'id'
id_type = 'id_type'
last_name = 'last_name'
office_phone = 'office_phone'
question_1 = 'question_1'
question_2 = 'question_2'
salt = 'salt'
users = 'users'

# clients
buyer = 'buyer'
buyer_approval = 'buyer_approval'
buyer_rate = 'rate'
client = 'client'
client_id = 'client_id'
client_open_invoices = 'client_open_invoices'
client_relations = 'client_relations'
client_size = 'client_size'
client_status = 'client_status'
client_type = 'client_type'
client_zip = 'client_zip'
supplier = 'supplier'
supplier_approval = 'supplier_approval'
supplier_rate = 'rate'

# for payments page
credit = 'credit'
debit = 'debit'
payment_date = 'payment_date'

# for invoices
accrual_period = 'accrual_period'
applied_rate = 'applied_rate'
approved_by = 'approved_by'
approved_on = 'approved_on'
buyer_id = 'buyer_id'
buyer_fraction = 'buyer_fraction'
buyer_name = 'buyer_name'
client_name = 'client_name'
cancelled_by = 'cancelled_by'
cancelled_timestamp = 'cancelled_timestamp'
completion_date = 'completion_date'
financing_details = 'financing_details'
financing_product = 'financing_product'
financing_product_id = 'financing_product_id'
invoice_ref_id = 'invoice_ref_id'
invoice_date = 'invoice_date'
invoice_percentage = 'invoice_percentage'
invoice_status = 'invoice_status'
invoice_total = 'invoice_total'
paid_by = 'paid_by'
paid_to = 'paid_to'
payment_type = 'payment_type'
principal_due = 'principal_due'
remaining_financing = 'remaining_financing'
repayment_details = 'repayment_details'
repayment_due = 'repayment_due'
submitted_by = 'submitted_by'
submission_overridden = 'submission_overridden'
submission_timestamp = 'submission_timestamp'
submitted_on = 'submitted_on'
supplier_id = 'supplier_id'
supplier_fraction = 'supplier_fraction'
supplier_name = 'supplier_name'
total_discount_fees = 'total_discount_fees'
total_financed = 'total_financed'
total_repayments = 'total_repayments'
total_transaction_cost = 'total_transaction_cost'
unrealized_pnl = 'unrealized_pnl'

# invoice_status
cancelled_status = 'CANCELLED'
closed_status = 'CLOSED'
open_status = 'OPEN'

# for forwarded payments
financed_amount = 'financed_amount'
financing_date = 'financing_date'
transaction_cost = 'transaction_cost'

# for received payments
discount_fees = 'discount_fees'
principal_repaid = 'principal_repaid'
repaid_amount = 'repaid_amount'
repayment_date = 'repayment_date'

# for rates
base_rate = 'base_rate'
end_period = 'end_period'
start_period = 'start_period'

# limit types
client_limits = 'client_limits'
discounting_max_giv = 'discounting_max_giv'
discounting_max_single_iv = 'discounting_max_single_iv'
discounting_max_invoice_count = 'discounting_max_invoice_count'
invoicing_max_giv = 'invoicing_max_giv'
invoicing_max_single_iv = 'invoicing_max_single_iv'
invoicing_max_invoice_count = 'invoicing_max_invoice_count'
limit_id = 'limit_id'
limit_type = 'limit_type'
relation_limits = 'relation_limits'
relation_max_giv = 'relation_max_giv'
relation_max_single_iv = 'relation_max_single_iv'
relation_max_invoice_count = 'relation_max_invoice_count'

# reports
chart_type = 'chart_type'
labels = 'labels'
report_type = 'report_type'
timeline = 'timeline'
values = 'values'

# internal
rm_id = 'rm_id'
rm_name = 'rm_name'
rm_username = 'rm_username'

# payments
financing_invoice_id = 'financing_invoice_id'
financing_notes = 'financing_notes'
financing_payment_type = 'financing_payment_type'
financing_transaction_cost = 'financing_transaction_cost'
payment_id = 'payment_id'
repayment_invoice_id = 'repayment_invoice_id'
repayment_notes = 'repayment_notes'
repayment_payment_type = 'repayment_payment_type'
repayment_transaction_cost = 'repayment_transaction_cost'
side = 'side'

